### ISSUE TITLE
No support for binary numbers with 0b prefix.

### ISSUE THREAD

**Issue by mcourteaux** [rluba/jai.vim#6]

**Comment by rjurga** [comment]
It seems to be handled in line 81 of `jai.vim`:

```
syntax match jaiBinary "\<0[b\|B][0-1_]\+\>" display
```

I tested it quickly and it's highlighted properly. It also works in `002_number_types.jai`. Are there specific situations where it fails to highlight?

**Comment by mcourteaux** [comment]
Huh, in that case, I apologize, will debug on my end here...

**Comment by mcourteaux** [comment]
Yeah, I saw this on the only computer where I hadn't upgraded to your fork yet. Sorry for wasting your time.
