### ISSUE TITLE
Comments break brace indentation

### ISSUE THREAD

**Issue by MintPaw** [rluba/jai.vim#9]
Commenting out braces, or even commenting after them causes weird intention effects, shown here:

```
{ // A comment
myVar := 5;
}
```

```
// {
	// 	myVar := 5;
	// }
```

These are the results after running auto indent.

**Comment by rluba** [comment]
That‘s not great. 

Unfortunately, I’m not the original author of this module, I’m not a VIM expert, and my patience for wrestling with VIM configuration is quite limited. But [line 45 in `indent/jai.vim`](https://github.com/rluba/jai.vim/blob/55baccc0fdb7c41896a018984e00b33cd03172ac/indent/jai.vim#L45) is definitely wrong and breaks when there’s a trailing comment. I’ll experiment a bit.
